### ISSUE TITLE
change the default export to a named export

### ISSUE THREAD

**Issue by targos** [mljs/savitzky-golay-generalized#7]
https://github.com/mljs/savitzky-golay-generalized/blob/4d297fb41b71ddc2e20ac856609a625e676d31d4/src/index.js#L12

This is a breaking change.
@lpatiny what name should we use? we should avoid conflict with https://github.com/mljs/savitzky-golay/blob/main/src/index.ts#L18

**Comment by lpatiny** [comment]
closed by 6711a31aecee25d03eadd4e235bc25b184043b5d

Finally I used `sgg` and `SGGOptions`
